"""full

Revision ID: 275923be553
Revises: None
Create Date: 2015-01-28 12:58:35.010000

"""

# revision identifiers, used by Alembic.
revision = '275923be553'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.Column('testimonial', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=30), nullable=False),
    sa.Column('lname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    op.drop_table('friendRequest')
    op.drop_table('testimonials')
    op.drop_table('friends')
    ### end Alembic commands ###
