"""added friendrequestfriends and message table

Revision ID: 33c1ef7dc76
Revises: 19142aa3ada
Create Date: 2015-01-25 17:32:43.938636

"""

# revision identifiers, used by Alembic.
revision = '33c1ef7dc76'
down_revision = '19142aa3ada'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friendRequest')
    op.drop_table('friends')
    ### end Alembic commands ###
