"""Added testimonial table

Revision ID: 464347c065c
Revises: 33c1ef7dc76
Create Date: 2015-01-26 13:49:53.786193

"""

# revision identifiers, used by Alembic.
revision = '464347c065c'
down_revision = '33c1ef7dc76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.Column('testimonial', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    ### end Alembic commands ###
