"""Added not null for userfields

Revision ID: 47af2d5948a
Revises: 1881948ddda
Create Date: 2015-01-23 07:26:57.526218

"""

# revision identifiers, used by Alembic.
revision = '47af2d5948a'
down_revision = '1881948ddda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
