"""sfsdf

Revision ID: 4b364825482d
Revises: None
Create Date: 2015-01-31 09:59:09.048000

"""

# revision identifiers, used by Alembic.
revision = '4b364825482d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phoneno', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneno')
    op.drop_column('users', 'address')
    ### end Alembic commands ###
