"""added address and phno

Revision ID: 4d04ca64aa3a
Revises: 275923be553
Create Date: 2015-01-28 13:46:02.373000

"""

# revision identifiers, used by Alembic.
revision = '4d04ca64aa3a'
down_revision = '275923be553'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phoneno', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneno')
    op.drop_column('users', 'address')
    ### end Alembic commands ###
