"""init

Revision ID: 648e7eadc9b
Revises: None
Create Date: 2015-01-27 10:38:19.981000

"""

# revision identifiers, used by Alembic.
revision = '648e7eadc9b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=False),
    sa.Column('testimonial', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    op.drop_table('messages')
    op.drop_table('friends')
    op.drop_table('friendRequest')
    ### end Alembic commands ###
